### ISSUE TITLE
WebApp

### ISSUE THREAD

**Issue by larchanka** [Mia-v/Tasks#1]
```css
*{
	box-sizing: border-box;
}

html {
	font-size: 16px;
}

body {
	margin: 0;
	padding: 0;
	font-family: 'Dancing Script', cursive;
}

.wrapper{
	display: flex;
}

header,
footer{
	display: fixed;
	width: 100%;
	height: 50px;
	padding: 10px;
}

header{
	background-color: lightgreen;
}

.items{
	height: 100px;
	padding: 10px;
	margin: 10px;
}

.first {
	background-color: lightseagreen;
	width: 20%;
	font-size: 2rem;
}

.second {
	background-color: yellow;
	width: 50%;
	font-size: 2rem;
}

.third {
	background-color: lightsalmon;
	width: 30%;
	font-size: 2rem;
}

footer{
	background-color: aqua;
}

@media (max-width: 768px) and (min-width: 480px){
	.first{
		width: 40%;
	}
	.second{
		width: 60%;
	}
	.third{
		display: none;
	}
}

@media (max-width: 479px){
	.wrapper{
		flex-direction: column;
	}
	
	.first{
		width: 100%;
		margin: 0;
	}
	
	.second{
		width: 100%;
		order: -1;
		margin: 0;
	}
	
	.third{
		width: 100%;
		margin: 0;
	}
}
```
